apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ant-nodejs 
  janus-idp.io/tekton: ant-nodejs
  backstage.io/kubernetes-id: ant-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ant-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  